### ISSUE TITLE
希望Markdown能够支持群@

### ISSUE THREAD

**Issue by YY-HakunaMatata** [jenkinsci/wxwork-notification-plugin#19]
### What feature do you want to see added?

希望Markdown能够支持群@;

**Comment by nekoimi** [comment]
@YY-HakunaMatata 目前微信机器人@成员只能使用userId来@，不能直接使用手机号来@，这个普通企业微信用户获取不到这个userId，需要管理员登录到企业微信后台查看，这个有点麻烦  https://developer.work.weixin.qq.com/document/path/91770?version=4.0.8.6027&platform=win
