### ISSUE TITLE
希望能自定义结束通知内容

### ISSUE THREAD

**Issue by miracleQin** [jenkinsci/wxwork-notification-plugin#29]
### What feature do you want to see added?

我在用 maven 构建 jar 包之后，通过 maven 插件将构建好的 jar 包版本信息赋值给一个环境变量(POM_VERSION)，然后希望能在构建任务结束之后，将这个环境变量信息通知到企业微信群中。

**Comment by nekoimi** [comment]
@miracleQin 
可以直接使用环境变量的。${ENV_NAME} 就行了

`            wxwork(
                robot: 'test',
                type: 'text',
                text: [
                    '${JOB_NAME}-${BUILD_NUMBER} build end'
                ]
            )
`
