### ISSUE TITLE
Uncaught ReferenceError: Ajax is not defined

### ISSUE THREAD

**Issue by YuYongzhi** [jenkinsci/wxwork-notification-plugin#34]
### Jenkins and plugins versions report

```text
  Uncaught ReferenceError: Ajax is not defined
    at wxworkSendRobotTest (configure:125:17)
    at HTMLInputElement.onclick (configure:165:647)
  ```
![image](https://github.com/user-attachments/assets/c19e0e1c-3654-478a-9dd8-6f8210df146b)

### What Operating System are you using (both controller, and any agents involved in the problem)?

macOS:14.4.1
Jenkins： Jenkins 2.426.2
  

### Reproduction steps

进入设置，点击“测试”，console报错

### Expected Results

点击“测试”，企业微信能收到通知

### Actual Results

企业微信无通知

**Comment by nekoimi** [comment]
我看下

**Comment by nekoimi** [comment]
已修复：https://github.com/jenkinsci/wxwork-notification-plugin/pull/44
请安装最新版插件。
