### ISSUE TITLE
Improper versioning scheme

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/wxwork-notification-plugin#4]
### Jenkins and plugins versions report

n/a

### What Operating System are you using (both controller, and any agents involved in the problem)?

n/a

### Reproduction steps

n/a

### Expected Results

n/a

### Actual Results

n/a

### Anything else?

https://github.com/jenkinsci/wxwork-notification-plugin/blob/3e55c42b449d91384198f83a99bca6f9e76aa5f1/pom.xml#L19-L20 does not follow CD versioning formats recommended by https://www.jenkins.io/doc/developer/publishing/releasing-cd/#update-maven-pom-and-config, so the current release has a "rc" (release candidate) version number.

**Comment by nekoimi** [comment]
ok, already fixed
