### ISSUE TITLE
Unexpected compatibleSince attribute

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/wxwork-notification-plugin#5]
### Jenkins and plugins versions report

n/a

### What Operating System are you using (both controller, and any agents involved in the problem)?

n/a

### Reproduction steps

n/a

### Expected Results

n/a

### Actual Results

n/a

### Anything else?

https://github.com/jenkinsci/wxwork-notification-plugin/blob/3e55c42b449d91384198f83a99bca6f9e76aa5f1/pom.xml#L21 should be deleted. https://www.jenkins.io/doc/developer/plugin-development/mark-a-plugin-incompatible/ does simply not apply for a new plugin.

**Comment by nekoimi** [comment]
ok, already fixed
