### ISSUE TITLE
请问在哪里配置在什么情况下才发送通知呢？

### ISSUE THREAD

**Issue by zonewancheng** [jenkinsci/wxwork-notification-plugin#50]
### What feature do you want to see added?

必须要修改Jenkinsfile吗？
比如我只想某个job在构建失败的情况下发送通知，应该在哪里配置呢？

**Comment by zonewancheng** [comment]
文档能否再详细点，感谢🙏

**Comment by nekoimi** [comment]
@zonewancheng  目前只支持消息发送，不支持配置某个job失败发送

**Comment by zonewancheng** [comment]
> @zonewancheng 目前不支持直接配置某个job失败 、成功发送，有空更新下。 可以先在Jenkinsfile中根据job状态调用 wxwork 函数实现发送消息，可以参考文档中声明式写法部分：https://github.com/jenkinsci/wxwork-notification-plugin/blob/master/README.md

感谢答复，不过我这边不方便配置Jenkinsfile 😅
