### ISSUE TITLE
请问作者，有声明式的template吗

### ISSUE THREAD

**Issue by rookie-fpc** [jenkinsci/wxwork-notification-plugin#51]
### What feature do you want to see added?

请问作者，有声明式的template吗

**Comment by rookie-fpc** [comment]
有声明式的jenkinsfile  template吗，谢谢

**Comment by nekoimi** [comment]
@rookie-fpc 查看最新README说明：https://github.com/jenkinsci/wxwork-notification-plugin/blob/master/README.md
最新添加了声明式写法的消息发送用法
